### ISSUE TITLE
vue add成功后运行项目报错

### ISSUE THREAD

**Issue by HeMiaoQ** [ElementUI/vue-cli-plugin-element#51]
![image](https://user-images.githubusercontent.com/41939836/96820430-8d959480-1458-11eb-85fb-2c82c8dc8b89.png)

**Comment by mengxzh** [comment]
me too

**Comment by fallenwood** [comment]
+1

**Comment by MangoSeven** [comment]
同问

**Comment by MangoSeven** [comment]
me too

**Comment by Towering-White** [comment]
+1

**Comment by chuanzhangjiang** [comment]
执行"vue create 项目名称"的时候，这样选就没问题。
![element-add-erro](https://user-images.githubusercontent.com/13307697/101645281-274ceb80-3a71-11eb-94c9-1cd7e6736638.png)

**Comment by HeMiaoQ** [comment]
> 执行"vue create 项目名称"的时候，这样选就没问题。
> ![element-add-erro](https://user-images.githubusercontent.com/13307697/101645281-274ceb80-3a71-11eb-94c9-1cd7e6736638.png)

可是这个是element UI的Vue 3版本啊，就是为了用3.x才用这个的

**Comment by i-curve** [comment]
+1

**Comment by starock** [comment]
_使用 vue-cli@3
我们为新版的 vue-cli 准备了相应的 Element 插件，你可以用它们快速地搭建一个基于 Element 的项目。_

文档说的是vue-cli 3, 并不是vue 3.
